include(":sample")
include(":sample-compose")
include(":libraries:rating-bar")
include(":libraries:dialogs")
include(":libraries:image-slider")
include(":libraries:phonenumber")
include(":libraries:toolbar")
include(":libraries:suggestion-input-view")
include(":libraries:card-input-view")
include(":libraries:quantity-picker-view")
include(":libraries:timeline-view")
include(":libraries:touch-delegator")
include(":libraries:fit-option-message-view")
include(":libraries:fit-option-message-view-compose")
include(":libraries:timeline-view-compose")
include(":libraries:rating-bar-compose")

rootProject.name = "trendyol-android-ui-components"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
